[package]
name = "mgr"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = {version = "0.8.0", features = ["dynamic"]}
bevy-inspector-egui = "0.12.0"
image = "0.24.3"
serde = "1.0.143"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
