[package]
name = "mgr"
version = "0.0.2"
authors = ["Frankie Lyons <frankiejlyons@gmail.com>"]
edition = "2021"


[dependencies]
macroquad = "0.4.13"
bevy =  "0.15.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3