[package]
name = "mgr"
version = "0.0.1"
authors = ["Frankie Lyons <frankiejlyons@gmail.com>"]
edition = "2021"


[dependencies]
macroquad = "0.3.25"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
